"""
Error codes and categories for BotsPool

This module defines standardized error codes and categories used throughout
the BotsPool platform for consistent error handling and reporting.
"""

from enum import Enum
from typing import Dict, Optional


class ErrorSeverity(str, Enum):
    """Error severity levels for prioritization and handling."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ErrorCategory(str, Enum):
    """Error categories for grouping related errors."""

    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    VALIDATION = "validation"
    GRAPH = "graph"
    DATABASE = "database"
    EXTERNAL_SERVICE = "external_service"
    RATE_LIMIT = "rate_limit"
    SUBSCRIPTION = "subscription"
    CONFIGURATION = "configuration"
    INTERNAL = "internal"
    UNKNOWN = "unknown"


class ErrorCode(str, Enum):
    """Standardized error codes for the BotsPool platform.

    Format: SERVICE_ACTION_NUMBER
    - SERVICE: The service or component (AUTH, GRAPH, DATABASE, etc.)
    - ACTION: The action or operation (LOGIN, CREATE, UPDATE, etc.)
    - NUMBER: Sequential number for specific error types
    """

    # Authentication Errors (AUTH_*)
    AUTH_TOKEN_EXPIRED_001 = "AUTH_TOKEN_EXPIRED_001"
    AUTH_INVALID_TOKEN_002 = "AUTH_INVALID_TOKEN_002"
    AUTH_INSUFFICIENT_PERMISSIONS_003 = "AUTH_INSUFFICIENT_PERMISSIONS_003"
    AUTH_LOGIN_FAILED_004 = "AUTH_LOGIN_FAILED_004"
    AUTH_USER_NOT_FOUND_005 = "AUTH_USER_NOT_FOUND_005"
    AUTH_PASSWORD_INCORRECT_006 = "AUTH_PASSWORD_INCORRECT_006"
    AUTH_ACCOUNT_LOCKED_007 = "AUTH_ACCOUNT_LOCKED_007"
    AUTH_ACCOUNT_SUSPENDED_008 = "AUTH_ACCOUNT_SUSPENDED_008"
    AUTH_MFA_REQUIRED_009 = "AUTH_MFA_REQUIRED_009"
    AUTH_MFA_INVALID_010 = "AUTH_MFA_INVALID_010"

    # Authorization Errors (AUTHZ_*)
    AUTHZ_ACCESS_DENIED_001 = "AUTHZ_ACCESS_DENIED_001"
    AUTHZ_ROLE_INSUFFICIENT_002 = "AUTHZ_ROLE_INSUFFICIENT_002"
    AUTHZ_RESOURCE_FORBIDDEN_003 = "AUTHZ_RESOURCE_FORBIDDEN_003"
    AUTHZ_OPERATION_NOT_ALLOWED_004 = "AUTHZ_OPERATION_NOT_ALLOWED_004"

    # Validation Errors (VALIDATION_*)
    VALIDATION_INVALID_INPUT_001 = "VALIDATION_INVALID_INPUT_001"
    VALIDATION_MISSING_FIELD_002 = "VALIDATION_MISSING_FIELD_002"
    VALIDATION_INVALID_FORMAT_003 = "VALIDATION_INVALID_FORMAT_003"
    VALIDATION_VALUE_TOO_LONG_004 = "VALIDATION_VALUE_TOO_LONG_004"
    VALIDATION_VALUE_TOO_SHORT_005 = "VALIDATION_VALUE_TOO_SHORT_005"
    VALIDATION_INVALID_EMAIL_006 = "VALIDATION_INVALID_EMAIL_006"
    VALIDATION_INVALID_PASSWORD_007 = "VALIDATION_INVALID_PASSWORD_007"
    VALIDATION_INVALID_USERNAME_008 = "VALIDATION_INVALID_USERNAME_008"
    VALIDATION_DUPLICATE_VALUE_009 = "VALIDATION_DUPLICATE_VALUE_009"
    VALIDATION_OUT_OF_RANGE_010 = "VALIDATION_OUT_OF_RANGE_010"

    # Graph Errors (GRAPH_*)
    GRAPH_SERVICE_UNAVAILABLE_001 = "GRAPH_SERVICE_UNAVAILABLE_001"
    GRAPH_REQUEST_TIMEOUT_002 = "GRAPH_REQUEST_TIMEOUT_002"
    GRAPH_PROCESSING_ERROR_003 = "GRAPH_PROCESSING_ERROR_003"
    GRAPH_INVALID_RESPONSE_004 = "GRAPH_INVALID_RESPONSE_004"
    GRAPH_NO_INSTANCES_AVAILABLE_005 = "GRAPH_NO_INSTANCES_AVAILABLE_005"
    GRAPH_LOAD_BALANCE_FAILED_006 = "GRAPH_LOAD_BALANCE_FAILED_006"
    GRAPH_HEALTH_CHECK_FAILED_007 = "GRAPH_HEALTH_CHECK_FAILED_007"
    GRAPH_CONFIGURATION_ERROR_008 = "GRAPH_CONFIGURATION_ERROR_008"
    GRAPH_MEMORY_ERROR_009 = "GRAPH_MEMORY_ERROR_009"
    GRAPH_TOOL_ERROR_010 = "GRAPH_TOOL_ERROR_010"

    # Database Errors (DATABASE_*)
    DATABASE_CONNECTION_FAILED_001 = "DATABASE_CONNECTION_FAILED_001"
    DATABASE_QUERY_FAILED_002 = "DATABASE_QUERY_FAILED_002"
    DATABASE_TRANSACTION_FAILED_003 = "DATABASE_TRANSACTION_FAILED_003"
    DATABASE_CONSTRAINT_VIOLATION_004 = "DATABASE_CONSTRAINT_VIOLATION_004"
    DATABASE_DEADLOCK_005 = "DATABASE_DEADLOCK_005"
    DATABASE_TIMEOUT_006 = "DATABASE_TIMEOUT_006"
    DATABASE_POOL_EXHAUSTED_007 = "DATABASE_POOL_EXHAUSTED_007"
    DATABASE_MIGRATION_FAILED_008 = "DATABASE_MIGRATION_FAILED_008"
    DATABASE_BACKUP_FAILED_009 = "DATABASE_BACKUP_FAILED_009"
    DATABASE_RESTORE_FAILED_010 = "DATABASE_RESTORE_FAILED_010"

    # External Service Errors (EXTERNAL_*)
    EXTERNAL_OPENAI_ERROR_001 = "EXTERNAL_OPENAI_ERROR_001"
    EXTERNAL_REDIS_ERROR_001 = "EXTERNAL_REDIS_ERROR_001"
    EXTERNAL_POSTGRES_ERROR_001 = "EXTERNAL_POSTGRES_ERROR_001"
    EXTERNAL_STRIPE_ERROR_001 = "EXTERNAL_STRIPE_ERROR_001"
    EXTERNAL_TELEGRAM_ERROR_001 = "EXTERNAL_TELEGRAM_ERROR_001"
    EXTERNAL_DISCORD_ERROR_001 = "EXTERNAL_DISCORD_ERROR_001"
    EXTERNAL_EMAIL_ERROR_001 = "EXTERNAL_EMAIL_ERROR_001"
    EXTERNAL_SMS_ERROR_001 = "EXTERNAL_SMS_ERROR_001"
    EXTERNAL_WEBHOOK_ERROR_001 = "EXTERNAL_WEBHOOK_ERROR_001"
    EXTERNAL_API_ERROR_001 = "EXTERNAL_API_ERROR_001"

    # Rate Limiting Errors (RATE_*)
    RATE_LIMIT_EXCEEDED_001 = "RATE_LIMIT_EXCEEDED_001"
    RATE_LIMIT_QUOTA_EXCEEDED_002 = "RATE_LIMIT_QUOTA_EXCEEDED_002"
    RATE_LIMIT_BURST_EXCEEDED_003 = "RATE_LIMIT_BURST_EXCEEDED_003"
    RATE_LIMIT_GLOBAL_EXCEEDED_004 = "RATE_LIMIT_GLOBAL_EXCEEDED_004"
    RATE_LIMIT_USER_EXCEEDED_005 = "RATE_LIMIT_USER_EXCEEDED_005"
    RATE_LIMIT_IP_EXCEEDED_006 = "RATE_LIMIT_IP_EXCEEDED_006"
    RATE_LIMIT_GRAPH_EXCEEDED_007 = "RATE_LIMIT_GRAPH_EXCEEDED_007"
    RATE_LIMIT_SUBSCRIPTION_EXCEEDED_008 = "RATE_LIMIT_SUBSCRIPTION_EXCEEDED_008"

    # Subscription Errors (SUBSCRIPTION_*)
    SUBSCRIPTION_LIMIT_EXCEEDED_001 = "SUBSCRIPTION_LIMIT_EXCEEDED_001"
    SUBSCRIPTION_EXPIRED_002 = "SUBSCRIPTION_EXPIRED_002"
    SUBSCRIPTION_CANCELLED_003 = "SUBSCRIPTION_CANCELLED_003"
    SUBSCRIPTION_PAYMENT_FAILED_004 = "SUBSCRIPTION_PAYMENT_FAILED_004"
    SUBSCRIPTION_UPGRADE_FAILED_005 = "SUBSCRIPTION_UPGRADE_FAILED_005"
    SUBSCRIPTION_DOWNGRADE_FAILED_006 = "SUBSCRIPTION_DOWNGRADE_FAILED_006"
    SUBSCRIPTION_BILLING_ERROR_007 = "SUBSCRIPTION_BILLING_ERROR_007"
    SUBSCRIPTION_PLAN_NOT_FOUND_008 = "SUBSCRIPTION_PLAN_NOT_FOUND_008"
    SUBSCRIPTION_FEATURE_NOT_AVAILABLE_009 = "SUBSCRIPTION_FEATURE_NOT_AVAILABLE_009"
    SUBSCRIPTION_GRAPH_ACCESS_DENIED_010 = "SUBSCRIPTION_GRAPH_ACCESS_DENIED_010"

    # Configuration Errors (CONFIG_*)
    CONFIG_INVALID_VALUE_001 = "CONFIG_INVALID_VALUE_001"
    CONFIG_MISSING_VALUE_002 = "CONFIG_MISSING_VALUE_002"
    CONFIG_ENVIRONMENT_ERROR_003 = "CONFIG_ENVIRONMENT_ERROR_003"
    CONFIG_FILE_NOT_FOUND_004 = "CONFIG_FILE_NOT_FOUND_004"
    CONFIG_PARSE_ERROR_005 = "CONFIG_PARSE_ERROR_005"
    CONFIG_VALIDATION_ERROR_006 = "CONFIG_VALIDATION_ERROR_006"
    CONFIG_RELOAD_ERROR_007 = "CONFIG_RELOAD_ERROR_007"
    CONFIG_SECRET_ERROR_008 = "CONFIG_SECRET_ERROR_008"

    # Internal Errors (INTERNAL_*)
    INTERNAL_SERVER_ERROR_001 = "INTERNAL_SERVER_ERROR_001"
    INTERNAL_PROCESSING_ERROR_002 = "INTERNAL_PROCESSING_ERROR_002"
    INTERNAL_MEMORY_ERROR_003 = "INTERNAL_MEMORY_ERROR_003"
    INTERNAL_TIMEOUT_ERROR_004 = "INTERNAL_TIMEOUT_ERROR_004"
    INTERNAL_QUEUE_ERROR_005 = "INTERNAL_QUEUE_ERROR_005"
    INTERNAL_CACHE_ERROR_006 = "INTERNAL_CACHE_ERROR_006"
    INTERNAL_LOGGING_ERROR_007 = "INTERNAL_LOGGING_ERROR_007"
    INTERNAL_MONITORING_ERROR_008 = "INTERNAL_MONITORING_ERROR_008"

    # Unknown Errors (UNKNOWN_*)
    UNKNOWN_ERROR_001 = "UNKNOWN_ERROR_001"
    UNKNOWN_SERVICE_ERROR_002 = "UNKNOWN_SERVICE_ERROR_002"
    UNKNOWN_NETWORK_ERROR_003 = "UNKNOWN_NETWORK_ERROR_003"


# Error code to category mapping
ERROR_CODE_CATEGORIES: Dict[ErrorCode, ErrorCategory] = {
    # Authentication
    ErrorCode.AUTH_TOKEN_EXPIRED_001: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_INVALID_TOKEN_002: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS_003: ErrorCategory.AUTHORIZATION,
    ErrorCode.AUTH_LOGIN_FAILED_004: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_USER_NOT_FOUND_005: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_PASSWORD_INCORRECT_006: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_ACCOUNT_LOCKED_007: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_ACCOUNT_SUSPENDED_008: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_MFA_REQUIRED_009: ErrorCategory.AUTHENTICATION,
    ErrorCode.AUTH_MFA_INVALID_010: ErrorCategory.AUTHENTICATION,
    # Authorization
    ErrorCode.AUTHZ_ACCESS_DENIED_001: ErrorCategory.AUTHORIZATION,
    ErrorCode.AUTHZ_ROLE_INSUFFICIENT_002: ErrorCategory.AUTHORIZATION,
    ErrorCode.AUTHZ_RESOURCE_FORBIDDEN_003: ErrorCategory.AUTHORIZATION,
    ErrorCode.AUTHZ_OPERATION_NOT_ALLOWED_004: ErrorCategory.AUTHORIZATION,
    # Validation
    ErrorCode.VALIDATION_INVALID_INPUT_001: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_MISSING_FIELD_002: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_INVALID_FORMAT_003: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_VALUE_TOO_LONG_004: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_VALUE_TOO_SHORT_005: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_INVALID_EMAIL_006: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_INVALID_PASSWORD_007: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_INVALID_USERNAME_008: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_DUPLICATE_VALUE_009: ErrorCategory.VALIDATION,
    ErrorCode.VALIDATION_OUT_OF_RANGE_010: ErrorCategory.VALIDATION,
    # Graph
    ErrorCode.GRAPH_SERVICE_UNAVAILABLE_001: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_REQUEST_TIMEOUT_002: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_PROCESSING_ERROR_003: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_INVALID_RESPONSE_004: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_NO_INSTANCES_AVAILABLE_005: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_LOAD_BALANCE_FAILED_006: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_HEALTH_CHECK_FAILED_007: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_CONFIGURATION_ERROR_008: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_MEMORY_ERROR_009: ErrorCategory.GRAPH,
    ErrorCode.GRAPH_TOOL_ERROR_010: ErrorCategory.GRAPH,
    # Database
    ErrorCode.DATABASE_CONNECTION_FAILED_001: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_QUERY_FAILED_002: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_TRANSACTION_FAILED_003: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_CONSTRAINT_VIOLATION_004: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_DEADLOCK_005: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_TIMEOUT_006: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_POOL_EXHAUSTED_007: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_MIGRATION_FAILED_008: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_BACKUP_FAILED_009: ErrorCategory.DATABASE,
    ErrorCode.DATABASE_RESTORE_FAILED_010: ErrorCategory.DATABASE,
    # External Service
    ErrorCode.EXTERNAL_OPENAI_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_REDIS_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_POSTGRES_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_STRIPE_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_TELEGRAM_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_DISCORD_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_EMAIL_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_SMS_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_WEBHOOK_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    ErrorCode.EXTERNAL_API_ERROR_001: ErrorCategory.EXTERNAL_SERVICE,
    # Rate Limiting
    ErrorCode.RATE_LIMIT_EXCEEDED_001: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_QUOTA_EXCEEDED_002: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_BURST_EXCEEDED_003: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_GLOBAL_EXCEEDED_004: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_USER_EXCEEDED_005: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_IP_EXCEEDED_006: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_GRAPH_EXCEEDED_007: ErrorCategory.RATE_LIMIT,
    ErrorCode.RATE_LIMIT_SUBSCRIPTION_EXCEEDED_008: ErrorCategory.RATE_LIMIT,
    # Subscription
    ErrorCode.SUBSCRIPTION_LIMIT_EXCEEDED_001: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_EXPIRED_002: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_CANCELLED_003: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_PAYMENT_FAILED_004: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_UPGRADE_FAILED_005: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_DOWNGRADE_FAILED_006: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_BILLING_ERROR_007: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_PLAN_NOT_FOUND_008: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_FEATURE_NOT_AVAILABLE_009: ErrorCategory.SUBSCRIPTION,
    ErrorCode.SUBSCRIPTION_GRAPH_ACCESS_DENIED_010: ErrorCategory.SUBSCRIPTION,
    # Configuration
    ErrorCode.CONFIG_INVALID_VALUE_001: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_MISSING_VALUE_002: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_ENVIRONMENT_ERROR_003: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_FILE_NOT_FOUND_004: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_PARSE_ERROR_005: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_VALIDATION_ERROR_006: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_RELOAD_ERROR_007: ErrorCategory.CONFIGURATION,
    ErrorCode.CONFIG_SECRET_ERROR_008: ErrorCategory.CONFIGURATION,
    # Internal
    ErrorCode.INTERNAL_SERVER_ERROR_001: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_PROCESSING_ERROR_002: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_MEMORY_ERROR_003: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_TIMEOUT_ERROR_004: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_QUEUE_ERROR_005: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_CACHE_ERROR_006: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_LOGGING_ERROR_007: ErrorCategory.INTERNAL,
    ErrorCode.INTERNAL_MONITORING_ERROR_008: ErrorCategory.INTERNAL,
    # Unknown
    ErrorCode.UNKNOWN_ERROR_001: ErrorCategory.UNKNOWN,
    ErrorCode.UNKNOWN_SERVICE_ERROR_002: ErrorCategory.UNKNOWN,
    ErrorCode.UNKNOWN_NETWORK_ERROR_003: ErrorCategory.UNKNOWN,
}

# Retryable error codes
RETRYABLE_ERROR_CODES: set[ErrorCode] = {
    # Graph errors (usually transient)
    ErrorCode.GRAPH_SERVICE_UNAVAILABLE_001,
    ErrorCode.GRAPH_REQUEST_TIMEOUT_002,
    ErrorCode.GRAPH_LOAD_BALANCE_FAILED_006,
    ErrorCode.GRAPH_HEALTH_CHECK_FAILED_007,
    # Database errors (usually transient)
    ErrorCode.DATABASE_CONNECTION_FAILED_001,
    ErrorCode.DATABASE_QUERY_FAILED_002,
    ErrorCode.DATABASE_TRANSACTION_FAILED_003,
    ErrorCode.DATABASE_DEADLOCK_005,
    ErrorCode.DATABASE_TIMEOUT_006,
    ErrorCode.DATABASE_POOL_EXHAUSTED_007,
    # External service errors (usually transient)
    ErrorCode.EXTERNAL_OPENAI_ERROR_001,
    ErrorCode.EXTERNAL_REDIS_ERROR_001,
    ErrorCode.EXTERNAL_POSTGRES_ERROR_001,
    ErrorCode.EXTERNAL_STRIPE_ERROR_001,
    ErrorCode.EXTERNAL_TELEGRAM_ERROR_001,
    ErrorCode.EXTERNAL_DISCORD_ERROR_001,
    ErrorCode.EXTERNAL_EMAIL_ERROR_001,
    ErrorCode.EXTERNAL_SMS_ERROR_001,
    ErrorCode.EXTERNAL_WEBHOOK_ERROR_001,
    ErrorCode.EXTERNAL_API_ERROR_001,
    # Rate limiting (retry after delay)
    ErrorCode.RATE_LIMIT_EXCEEDED_001,
    ErrorCode.RATE_LIMIT_QUOTA_EXCEEDED_002,
    ErrorCode.RATE_LIMIT_BURST_EXCEEDED_003,
    ErrorCode.RATE_LIMIT_GLOBAL_EXCEEDED_004,
    ErrorCode.RATE_LIMIT_USER_EXCEEDED_005,
    ErrorCode.RATE_LIMIT_IP_EXCEEDED_006,
    ErrorCode.RATE_LIMIT_GRAPH_EXCEEDED_007,
    ErrorCode.RATE_LIMIT_SUBSCRIPTION_EXCEEDED_008,
    # Internal errors (some are retryable)
    ErrorCode.INTERNAL_PROCESSING_ERROR_002,
    ErrorCode.INTERNAL_TIMEOUT_ERROR_004,
    ErrorCode.INTERNAL_QUEUE_ERROR_005,
    ErrorCode.INTERNAL_CACHE_ERROR_006,
}

# Default retry after seconds for retryable errors
DEFAULT_RETRY_AFTER: Dict[ErrorCode, int] = {
    # Graph errors
    ErrorCode.GRAPH_SERVICE_UNAVAILABLE_001: 30,
    ErrorCode.GRAPH_REQUEST_TIMEOUT_002: 10,
    ErrorCode.GRAPH_LOAD_BALANCE_FAILED_006: 5,
    ErrorCode.GRAPH_HEALTH_CHECK_FAILED_007: 15,
    # Database errors
    ErrorCode.DATABASE_CONNECTION_FAILED_001: 5,
    ErrorCode.DATABASE_QUERY_FAILED_002: 2,
    ErrorCode.DATABASE_TRANSACTION_FAILED_003: 3,
    ErrorCode.DATABASE_DEADLOCK_005: 1,
    ErrorCode.DATABASE_TIMEOUT_006: 5,
    ErrorCode.DATABASE_POOL_EXHAUSTED_007: 10,
    # External service errors
    ErrorCode.EXTERNAL_OPENAI_ERROR_001: 5,
    ErrorCode.EXTERNAL_REDIS_ERROR_001: 2,
    ErrorCode.EXTERNAL_POSTGRES_ERROR_001: 3,
    ErrorCode.EXTERNAL_STRIPE_ERROR_001: 10,
    ErrorCode.EXTERNAL_TELEGRAM_ERROR_001: 5,
    ErrorCode.EXTERNAL_DISCORD_ERROR_001: 5,
    ErrorCode.EXTERNAL_EMAIL_ERROR_001: 10,
    ErrorCode.EXTERNAL_SMS_ERROR_001: 10,
    ErrorCode.EXTERNAL_WEBHOOK_ERROR_001: 5,
    ErrorCode.EXTERNAL_API_ERROR_001: 5,
    # Rate limiting
    ErrorCode.RATE_LIMIT_EXCEEDED_001: 60,
    ErrorCode.RATE_LIMIT_QUOTA_EXCEEDED_002: 300,
    ErrorCode.RATE_LIMIT_BURST_EXCEEDED_003: 10,
    ErrorCode.RATE_LIMIT_GLOBAL_EXCEEDED_004: 60,
    ErrorCode.RATE_LIMIT_USER_EXCEEDED_005: 60,
    ErrorCode.RATE_LIMIT_IP_EXCEEDED_006: 300,
    ErrorCode.RATE_LIMIT_GRAPH_EXCEEDED_007: 30,
    ErrorCode.RATE_LIMIT_SUBSCRIPTION_EXCEEDED_008: 60,
    # Internal errors
    ErrorCode.INTERNAL_PROCESSING_ERROR_002: 2,
    ErrorCode.INTERNAL_TIMEOUT_ERROR_004: 5,
    ErrorCode.INTERNAL_QUEUE_ERROR_005: 3,
    ErrorCode.INTERNAL_CACHE_ERROR_006: 1,
}


def get_error_category(error_code: ErrorCode) -> ErrorCategory:
    """Get the category for an error code."""
    return ERROR_CODE_CATEGORIES.get(error_code, ErrorCategory.UNKNOWN)


def is_retryable_error(error_code: ErrorCode) -> bool:
    """Check if an error code represents a retryable error."""
    return error_code in RETRYABLE_ERROR_CODES


def get_retry_after_seconds(error_code: ErrorCode) -> Optional[int]:
    """Get the recommended retry after seconds for an error code."""
    return DEFAULT_RETRY_AFTER.get(error_code)


def get_error_code(code_string: str) -> Optional[ErrorCode]:
    """Get ErrorCode enum from string representation."""
    try:
        return ErrorCode(code_string)
    except ValueError:
        return None
