[tox]
envlist = \
    gateway-lint, gateway-tests, \
    notification-lint, notification-tests, \
    todo-lint, todo-tests, \
    telegram-lint, telegram-tests, \
    shared-utils-lint, shared-utils-tests
isolated_build = false
skip_missing_interpreters = true

[testenv]
passenv = *
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest

[testenv:gateway-tests]
changedir = {toxinidir}/botspool-gateway
deps =
    pytest
    pytest-asyncio
commands_pre =
    python -m pip install -r requirements.txt
commands = pytest {posargs}

[testenv:gateway-lint]
skip_install = true
changedir = {toxinidir}/botspool-gateway
deps =
    black==23.10.0
    flake8==6.1.0
commands =
    black --check src
    flake8 src

[testenv:notification-tests]
changedir = {toxinidir}/botspool-notification-service
deps =
    pytest
    pytest-asyncio
commands_pre =
    python -m pip install -r requirements.txt -r requirements-dev.txt
commands = pytest {posargs}

[testenv:notification-lint]
skip_install = true
changedir = {toxinidir}/botspool-notification-service
deps =
    black==23.10.0
    flake8==6.1.0
commands =
    black --check src
    flake8 src

[testenv:todo-tests]
changedir = {toxinidir}/botspool-todo-graph
deps =
    pytest
    pytest-asyncio
commands_pre =
    python -m pip install -r requirements.txt
commands = pytest {posargs}

[testenv:todo-lint]
skip_install = true
changedir = {toxinidir}/botspool-todo-graph
deps =
    black==23.10.0
    flake8==6.1.0
commands =
    black --check src
    flake8 src

[testenv:telegram-tests]
changedir = {toxinidir}/botspool-telegram
deps =
    pytest
    pytest-asyncio
commands_pre =
    python -m pip install -r requirements.txt -r requirements-dev.txt
commands = pytest {posargs}

[testenv:telegram-lint]
skip_install = true
changedir = {toxinidir}/botspool-telegram
deps =
    black==23.10.0
    flake8==6.1.0
commands =
    black --check src tests
    flake8 src tests

[testenv:shared-utils-tests]
changedir = {toxinidir}/botspool-shared-utils
deps =
    pytest
    pytest-asyncio
commands_pre =
    python -m pip install -r requirements.txt -r requirements-dev.txt
    python -m pip install pyotp qrcode pillow
    python -m pip install -e .
commands = pytest {posargs}

[testenv:shared-utils-lint]
skip_install = true
changedir = {toxinidir}/botspool-shared-utils
deps =
    black==23.10.0
    flake8==6.1.0
commands =
    black --check src tests
    flake8 src tests
