"""Initial schema: users, subscriptions, graphs

Revision ID: a915df10d70b
Revises: 
Create Date: 2025-11-01 19:12:28.094856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a915df10d70b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create UUID extension for PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    
    op.create_table('graph_health',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'UNHEALTHY', 'MAINTENANCE', 'OFFLINE', name='graphstatus'), nullable=False),
    sa.Column('response_time_avg', sa.Integer(), nullable=False),
    sa.Column('response_time_p95', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Integer(), nullable=False),
    sa.Column('cpu_usage', sa.Integer(), nullable=False),
    sa.Column('memory_usage', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_health_instance_id', 'graph_health', ['instance_id'], unique=False)
    op.create_index('idx_graph_health_last_health_check', 'graph_health', ['last_health_check'], unique=False)
    op.create_index('idx_graph_health_status', 'graph_health', ['status'], unique=False)
    op.create_index(op.f('ix_graph_health_instance_id'), 'graph_health', ['instance_id'], unique=True)
    op.create_table('graphs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_type', sa.Enum('TODO', 'EMAIL', 'CALENDAR', 'DOCUMENT', 'CODE', 'RESEARCH', name='graphtype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'UNHEALTHY', 'MAINTENANCE', 'OFFLINE', name='graphstatus'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('default_config', sa.JSON(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('last_deployment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('graph_type')
    )
    op.create_index('idx_graphs_graph_type', 'graphs', ['graph_type'], unique=False)
    op.create_index('idx_graphs_is_available', 'graphs', ['is_available'], unique=False)
    op.create_index('idx_graphs_status', 'graphs', ['status'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_index('idx_subscription_plans_is_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_index('idx_subscription_plans_tier', 'subscription_plans', ['tier'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'FREE_USER', 'BASIC_USER', 'PREMIUM_USER', 'ENTERPRISE_USER', 'ADMIN', 'DEVELOPER', name='userrole'), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_chats', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_last_activity', 'users', ['last_activity'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_subscription_tier', 'users', ['subscription_tier'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('frontend_type', sa.Enum('TELEGRAM', 'DISCORD', 'WEB', 'MOBILE', 'API', name='frontendtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ENDED', 'ERROR', name='chatstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('current_graph', sa.Enum('TODO', 'EMAIL', 'CALENDAR', 'DOCUMENT', 'CODE', 'RESEARCH', name='graphtype'), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frontend_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_current_graph', 'chat_sessions', ['current_graph'], unique=False)
    op.create_index('idx_chat_sessions_last_message_at', 'chat_sessions', ['last_message_at'], unique=False)
    op.create_index('idx_chat_sessions_session_id', 'chat_sessions', ['session_id'], unique=False)
    op.create_index('idx_chat_sessions_status', 'chat_sessions', ['status'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('graph_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'UNHEALTHY', 'MAINTENANCE', 'OFFLINE', name='graphstatus'), nullable=False),
    sa.Column('health_id', sa.UUID(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.String(length=255), nullable=True),
    sa.Column('container_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ),
    sa.ForeignKeyConstraint(['health_id'], ['graph_health.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_instances_graph_id', 'graph_instances', ['graph_id'], unique=False)
    op.create_index('idx_graph_instances_instance_id', 'graph_instances', ['instance_id'], unique=False)
    op.create_index('idx_graph_instances_last_heartbeat', 'graph_instances', ['last_heartbeat'], unique=False)
    op.create_index('idx_graph_instances_region', 'graph_instances', ['region'], unique=False)
    op.create_index('idx_graph_instances_status', 'graph_instances', ['status'], unique=False)
    op.create_index(op.f('ix_graph_instances_instance_id'), 'graph_instances', ['instance_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='uq_user_plan')
    )
    op.create_index('idx_subscriptions_is_active', 'subscriptions', ['is_active'], unique=False)
    op.create_index('idx_subscriptions_next_billing_date', 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index('idx_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('requests_current_minute', sa.Integer(), nullable=False),
    sa.Column('requests_current_hour', sa.Integer(), nullable=False),
    sa.Column('requests_current_day', sa.Integer(), nullable=False),
    sa.Column('requests_current_month', sa.Integer(), nullable=False),
    sa.Column('tokens_current_day', sa.Integer(), nullable=False),
    sa.Column('tokens_current_month', sa.Integer(), nullable=False),
    sa.Column('active_sessions', sa.Integer(), nullable=False),
    sa.Column('usage_by_graph', sa.JSON(), nullable=True),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_usage_tracking_last_reset_at', 'usage_tracking', ['last_reset_at'], unique=False)
    op.create_index('idx_usage_tracking_subscription_tier', 'usage_tracking', ['subscription_tier'], unique=False)
    op.create_index('idx_usage_tracking_user_id', 'usage_tracking', ['user_id'], unique=False)
    op.create_table('user_auth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'MICROSOFT', name='authprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_auth_email', 'user_auth', ['email'], unique=False)
    op.create_index('idx_user_auth_provider', 'user_auth', ['provider'], unique=False)
    op.create_index(op.f('ix_user_auth_email'), 'user_auth', ['email'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('default_graph', sa.String(length=50), nullable=True),
    sa.Column('auto_route', sa.Boolean(), nullable=False),
    sa.Column('chat_history_retention', sa.Integer(), nullable=False),
    sa.Column('data_sharing', sa.Boolean(), nullable=False),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('compact_mode', sa.Boolean(), nullable=False),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('beta_features', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_profile_display_name', 'user_profiles', ['display_name'], unique=False)
    op.create_index('idx_user_profile_username', 'user_profiles', ['username'], unique=False)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('frontend_type', sa.Enum('TELEGRAM', 'DISCORD', 'WEB', 'MOBILE', 'API', name='frontendtype'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_is_active', 'user_sessions', ['is_active'], unique=False)
    op.create_index('idx_user_sessions_session_id', 'user_sessions', ['session_id'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'ERROR', name='messagetype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graph_type', sa.Enum('TODO', 'EMAIL', 'CALENDAR', 'DOCUMENT', 'CODE', 'RESEARCH', name='graphtype'), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_graph_type', 'chat_messages', ['graph_type'], unique=False)
    op.create_index('idx_chat_messages_message_type', 'chat_messages', ['message_type'], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('idx_chat_messages_timestamp', 'chat_messages', ['timestamp'], unique=False)
    op.create_index('idx_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_timestamp', table_name='chat_messages')
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_message_type', table_name='chat_messages')
    op.drop_index('idx_chat_messages_graph_type', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_session_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_is_active', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index('idx_user_profile_username', table_name='user_profiles')
    op.drop_index('idx_user_profile_display_name', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_auth_email'), table_name='user_auth')
    op.drop_index('idx_user_auth_provider', table_name='user_auth')
    op.drop_index('idx_user_auth_email', table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index('idx_usage_tracking_user_id', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_subscription_tier', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_last_reset_at', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_next_billing_date', table_name='subscriptions')
    op.drop_index('idx_subscriptions_is_active', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_graph_instances_instance_id'), table_name='graph_instances')
    op.drop_index('idx_graph_instances_status', table_name='graph_instances')
    op.drop_index('idx_graph_instances_region', table_name='graph_instances')
    op.drop_index('idx_graph_instances_last_heartbeat', table_name='graph_instances')
    op.drop_index('idx_graph_instances_instance_id', table_name='graph_instances')
    op.drop_index('idx_graph_instances_graph_id', table_name='graph_instances')
    op.drop_table('graph_instances')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_status', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_session_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_last_message_at', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_current_graph', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('idx_users_subscription_tier', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_last_activity', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_subscription_plans_tier', table_name='subscription_plans')
    op.drop_index('idx_subscription_plans_is_active', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('idx_graphs_status', table_name='graphs')
    op.drop_index('idx_graphs_is_available', table_name='graphs')
    op.drop_index('idx_graphs_graph_type', table_name='graphs')
    op.drop_table('graphs')
    op.drop_index(op.f('ix_graph_health_instance_id'), table_name='graph_health')
    op.drop_index('idx_graph_health_status', table_name='graph_health')
    op.drop_index('idx_graph_health_last_health_check', table_name='graph_health')
    op.drop_index('idx_graph_health_instance_id', table_name='graph_health')
    op.drop_table('graph_health')
    # ### end Alembic commands ###
